name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: turbo lint

      - name: Check Types
        run: turbo typecheck

      - name: Build
        run: turbo build

      - name: Unit Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: turbo test
