name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Check Types
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Unit Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MC_VERSION: ${{ secrets.MC_VERSION }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          HONO_API_URL: ${{ secrets.HONO_API_URL }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        run: pnpm test
